data:
  dataset_root: '/Users/olega/Downloads/VisDrone2020-CC'

trainer:
  checkpoint_callback:
    filepath: './models/{epoch}-{val_loss:.4f}'
    monitor: 'val_loss'
    verbose: False
    save_last: True
    save_top_k: 1
    save_weights_only: False
    mode: 'min'
    period: 1
    prefix: ''

  fast_dev_run: False
  gpus: 0
  max_epochs: 100
  min_epochs: 1

