pipeline:
  model:
    name: 'FCNCastellano'
    params:
#      Castellano params
      in_channels: 3
      out_channels: 64

#      ResNet params
#      initial_size: 128
#      in_channels: 3
#      blocks_sizes: !!python/tuple [32, 64, 128, 256]
#      deepths: !!python/tuple [1, 1, 1, 1]
#      activation: 'relu'

  optimizer:
    - name: "SGD"
      params:
        lr: 10e-5
        momentum: 0.9

data:
  train:
    - name: "VisDroneDatasetСС"
      params:
#        data_root: '/Users/olega/Downloads/VisDrone2019-DET-train'
        data_root: '/Users/olega/Downloads/VisDrone2020-CC-split/train'
        im_folder: 'images'
        an_folder: 'annotations'
        resize: !!python/tuple [128, 128]
        normalize: True
    - name: "VisDroneDatasetDET"
      params:
        data_root: '/Users/olega/Downloads/VisDrone2019-DET-train'
        im_folder: 'images'
        an_folder: 'annotations'
        resize: !!python/tuple [128, 128]
        normalize: True
  val:
    - name: "VisDroneDatasetCC"
      params:
#        data_root: '/Users/olega/Downloads/VisDrone2019-DET-test-dev'
        data_root: '/Users/olega/Downloads/VisDrone2020-CC-split/val'
        im_folder: 'images'
        an_folder: 'annotations'
        resize: !!python/tuple [128, 128]
        normalize: True


dataloader:
  train:
    batch_size: 64
    num_workers: 5
    shuffle: True
  test:
    batch_size: 64
    num_workers: 5

trainer:
  checkpoint_callback:
    filepath: './models/{epoch}-{val_loss:.4f}'
    monitor: 'val_epoch_loss'
    verbose: True
    save_last: True
    save_top_k: 1
    save_weights_only: False
    mode: 'min'
    period: 1
    prefix: ''

#  callbacks:
#    - name: 'EarlyStopping'
#      params:
#        monitor: 'val_loss'
#        min_delta: 0.00
#        patience: 1
#        verbose: False
#        mode: 'max'

  fast_dev_run: True
  gpus: 0
  max_epochs: 100
  min_epochs: 1
  log_every_n_steps: 1

test:
  checkpoint_path: '/Users/olega/PycharmProjects/CrowdCounting/models/last.ckpt' # None or path to checkpoint
  resize: !!python/tuple [128, 128]  # same as in dataset!!!
  benchmark: True

