data:
  dataset_root: '/Users/olega/Downloads/VisDrone2020-CC'

dataloader:
  train:
    batch_size: 64
    num_workers: 5
    shuffle: True
  test:
    batch_size: 64
    num_workers: 5

trainer:
  checkpoint_callback:
    filepath: './models/{epoch}-{val_loss:.4f}'
    monitor: 'val_loss'
    verbose: True
    save_last: True
    save_top_k: 1
    save_weights_only: False
    mode: 'min'
    period: 1
    prefix: ''

  callbacks:
    - name: 'EarlyStopping'
      params:
        monitor: 'val_loss'
        min_delta: 0.00
        patience: 1
        verbose: False
        mode: 'max'

  fast_dev_run: False
  gpus: 0
  max_epochs: 100
  min_epochs: 1

test:
  checkpoint_path: '/Users/olega/PycharmProjects/CrowdCounting/models/last.ckpt' # None or path to checkpoint

