pipeline:
  model:
    load_model: 'path/to/model'
    name: 'FCNCastellanoBNSmall4'
    params:
      in_channels: 3
      out_channels: 32
  optimizers:
    - name: "SGD"
      params:
        lr: !!python/float 10e-5
        momentum: 0.9
  schedulers:
    - name: 'StepLR'
      params:
        step_size: 15
        gamma: 0.3
  criterions:
    mae:
      name: 'L1Loss'
    mse:
      name: 'MSELoss'
  data:
    train:
      transforms:
        - name: 'HorizontalFlip'
          params:
            p: 0.5
        - name: 'VerticalFlip'
          params:
            p: 0.5
        - name: 'RandomBrightnessContrast'
      dataloader:
        batch_size: 64
        num_workers: 5
        shuffle: True
      datasets:
        - name: "VisDroneDatasetCC"
          params:
            data_root: '/content/VisDrone2020-CC-split/train'
            im_folder: 'images'
            an_folder: 'annotations'
            resize: !!python/tuple [128, 128]
            normalize: True
#            weighted: 20
        - name: "VisDroneDatasetDET"
          params:
            data_root: '/content/VisDrone2019-DET-train'
            im_folder: 'images'
            an_folder: 'annotations'
            resize: !!python/tuple [128, 128]
            normalize: True
        - name: "VisDroneDatasetVID"
          params:
            data_root: '/content/VisDrone2019-VID-train'
            im_folder: 'sequences'
            an_folder: 'annotations'
            resize: !!python/tuple [128, 128]
            normalize: True
    val:
      dataloader:
        batch_size: 64
        num_workers: 5
        shuffle: False
      datasets:
        - name: "VisDroneDatasetCC"
          params:
            data_root: '/content/VisDrone2020-CC-split/val'
            im_folder: 'images'
            an_folder: 'annotations'
            resize: !!python/tuple [128, 128]
            normalize: True
#            weighted: 20
        - name: "VisDroneDatasetDET"
          params:
            data_root: '/content/VisDrone2019-DET-val'
            im_folder: 'images'
            an_folder: 'annotations'
            resize: !!python/tuple [128, 128]
            normalize: True
        - name: "VisDroneDatasetVID"
            params:
              data_root: '/content/VisDrone2019-VID-train'
              im_folder: 'sequences'
              an_folder: 'annotations'
              resize: !!python/tuple [ 128, 128 ]
              normalize: True
    test:
      dataloader:
        batch_size: 64
        num_workers: 5
        shuffle: False
      datasets:
        - name: "VisDroneDatasetCC"
          params:
            data_root: '/content/VisDrone2020-CC-split/val'
            im_folder: 'images'
            an_folder: 'annotations'
            resize: !!python/tuple [128, 128]
            normalize: True
#        - name: 'VisDroneDatasetVID'
#          params:
#            data_root: '/content/VisDrone2018-VID-val'
#            im_folder: 'sequences'
#            an_folder: 'annotations'
#            resize: !!python/tuple [128, 128]
#            normalize: True
        - name: 'VisDroneDatasetDET'
          params:
            data_root: '/content/VisDrone2019-DET-val'
            im_folder: 'images'
            an_folder: 'annotations'
            resize: !!python/tuple [128, 128]
            normalize: True

trainer:
  logger:
    name: 'TensorBoardLogger'
    params:
      save_dir: '/content/drive/MyDrive/Thesis_Colab/saved/logs/'
      name: 'bottlenecksmall4'
      version: 'full_dataset_final'
  checkpoint_callback:
    filepath: '/content/drive/MyDrive/Thesis_Colab/saved/models/bottlenecksmall4_ful/{epoch}-{val_loss:.4f}'
    monitor: 'val_loss'
    verbose: True
    save_last: True
    save_top_k: 3
    save_weights_only: False
    mode: 'min'
    period: 1
    prefix: ''

  callbacks:
    - name: 'EarlyStopping'
      params:
        monitor: 'val_loss'
        min_delta: 0.00
        patience: 5
        verbose: False
        mode: 'min'

  fast_dev_run: False
  gpus: 1
  max_epochs: 100
  min_epochs: 1
  log_every_n_steps: 1

test:
  checkpoint_path: 'path/to/model' # None or path to checkpoint
  resize: !!python/tuple [128, 128]  # same as in dataset!!!
  benchmark: True

