from torch.nn import (
    BCELoss,
    CosineEmbeddingLoss,
    CTCLoss,
    HingeEmbeddingLoss,
    KLDivLoss,
    MarginRankingLoss,
    MSELoss,
    MultiLabelMarginLoss,
    MultiLabelSoftMarginLoss,
    SmoothL1Loss,
    MultiMarginLoss,
    NLLLoss,
    PoissonNLLLoss,
    SoftMarginLoss,
    TripletMarginLoss,
    NLLLoss2d,
    L1Loss,
)
from .regression import MAEWeighted
